config/routes.rb
Rails.application.routes.draw do

   root 'posts#index', as:'home'

    get 'about' => 'pages#about', as:'about'

     resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true,
                        length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = "About Us"
        @content = "This is the about page."
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    
    def show
       @post = Post.find(params[:id]) 
    end 
    
    def new
        @post = Post.new
    end
    
    def create
        #render plain: params[:post].inspect
        @post = Post.new(post_params)
        
        if(@post.save)
            redirect_to @post
        else
            render 'new' 
        end
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.new(post_params[:id])
        
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit' 
        end
    end
    
    private def post_params
        params.require(:post).permit(:title, :body)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
      data-toggle="collapse" data-target="#navbar"
      aria-expanded="false" aria-controls="navabar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  
      <a class="navbar-brand" href="#">A Rails Blog!</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", home_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Create Post", new_post_path %></li>
      </ul>
    </div>
  </div>
</nav>  

<div class="container">

<%= yield %>

</div> 

</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert_danger"><%= msg %></div>
        <% end %>
    <% end %>
<p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :body %><br>
    <%= f.text_field(:body, {:class => 'form-control' }) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary' }) %>
</p>

<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
    <div class="well">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert_danger"><%= msg %></div>
        <% end %>
    <% end %>
<p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
    <%= f.label :body %><br>
    <%= f.text_field(:body, {:class => 'form-control' }) %>
</p>

<p>
    <%= f.submit({:class => 'btn btn-primary' }) %>
</p>

<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<b><%= @post.body %></b>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>